#-------------------------------------------------
#
# Project created by QtCreator 2015-02-07T18:57:15
#
#-------------------------------------------------

QT       += core gui
QT       -= opengl

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = win_opengles_01
TEMPLATE = app


SOURCES += \
    explore/cgdemo.cpp \
    explore/main.cpp \
    explore/mainactivity.cpp \
    explore/mainwindow.cpp \
    explore/winopengles.cpp \
    core/include/e3d_wallpaper_base/eScoreWidget2.cpp

HEADERS  += \
    explore/cgdemo.h \
    explore/mainactivity.h \
    explore/mainwindow.h \
    explore/winopengles.h \
    core/include/utils/CommonFunction.h \
    core/include/utils/TextureSplit.h \
    core/include/animation/AccelerateDecelerateInterpolator.h \
    core/include/animation/AccelerateInterpolator.h \
    core/include/animation/Animation.h \
    core/include/animation/AnimationManager.h \
    core/include/animation/AnimationSet.h \
    core/include/animation/AnimationUtils.h \
    core/include/animation/AnticipateInterpolator.h \
    core/include/animation/AnticipateOvershootInterpolator.h \
    core/include/animation/BounceInterpolator.h \
    core/include/animation/CycleInterpolator.h \
    core/include/animation/DecelerateInterpolator.h \
    core/include/animation/Interpolator.h \
    core/include/animation/InterpolatorSet.h \
    core/include/animation/KeyFramesManager.h \
    core/include/animation/KeyFramesRotateAnimation.h \
    core/include/animation/KeyFramesScaleAnimation.h \
    core/include/animation/KeyFramesTranslateAnimation.h \
    core/include/animation/LinearInterpolator.h \
    core/include/animation/OvershootInterpolator.h \
    core/include/animation/RotateAnimation.h \
    core/include/animation/ScaleAnimation.h \
    core/include/animation/SequenceFrameAnimation.h \
    core/include/animation/TexAlphaModifierAnimation.h \
    core/include/animation/TexCoordModifierAnimation.h \
    core/include/animation/TexCoordSetAnimation.h \
    core/include/animation/TranslateAnimation.h \
    core/include/asset/eMesh.h \
    core/include/asset/Font.h \
    core/include/asset/FontManager.h \
    core/include/asset/Image.h \
    core/include/asset/ImageCodec.h \
    core/include/asset/IMesh.h \
    core/include/asset/MaterialSerializer.h \
    core/include/asset/Mesh.h \
    core/include/asset/MeshManager.h \
    core/include/asset/OverlayPrerequisites.h \
    core/include/asset/Resource.h \
    core/include/asset/ResourceGroupManager.h \
    core/include/asset/ResourceManager.h \
    core/include/asset/SubMesh.h \
    core/include/asset/TangentSpaceCalc.h \
    core/include/assets/DefaultMaterials.h \
    core/include/base/Camera.h \
    core/include/base/ConfigOptionMap.h \
    core/include/base/Controller.h \
    core/include/base/ControllerManager.h \
    core/include/base/DepthBuffer.h \
    core/include/base/eCommon.h \
    core/include/base/FactoryObj.h \
    core/include/base/FrameListener.h \
    core/include/base/Frustum.h \
    core/include/base/HeaderPrefix.h \
    core/include/base/HeaderSuffix.h \
    core/include/base/ImageResampler.h \
    core/include/base/Light.h \
    core/include/base/LogManager.h \
    core/include/base/Object.h \
    core/include/base/PredefinedControllers.h \
    core/include/base/Root.h \
    core/include/base/Runnable.h \
    core/include/base/ScriptLoader.h \
    core/include/base/ScriptSupport.h \
    core/include/base/StringInterface.h \
    core/include/base/Viewport.h \
    core/include/component/Component.h \
    core/include/compositor/Compositor.h \
    core/include/compositor/CompositorChain.h \
    core/include/compositor/CompositorCustomPass.h \
    core/include/compositor/CompositorInstance.h \
    core/include/compositor/CompositorLogic.h \
    core/include/compositor/CompositorManager.h \
    core/include/compositor/CompositorPass.h \
    core/include/compositor/CompositorTargetPass.h \
    core/include/compositor/Rectangle2D.h \
    core/include/e3d_wallpaper_base/e3d_xml_parser_base.h \
    core/include/e3d_wallpaper_base/e3d_xml_parser_manager.h \
    core/include/e3d_wallpaper_base/e3d_xml_scene_parser.h \
    core/include/e3d_wallpaper_base/E3dWallpaperBase.h \
    core/include/e3d_wallpaper_base/Easy3dWallpaperJni.h \
    core/include/e3d_wallpaper_base/eRectDataSource.h \
    core/include/e3d_wallpaper_base/eScoreWidget.h \
    core/include/e3d_wallpaper_base/eScoreWidget2.h \
    core/include/e3d_wallpaper_base/SceneDataProvider.h \
    core/include/encrypt/Encrypt.h \
    core/include/hardwarebuffer/HardwareBuffer.h \
    core/include/hardwarebuffer/HardwareBufferManager.h \
    core/include/hardwarebuffer/HardwareIndexBuffer.h \
    core/include/hardwarebuffer/HardwareOcclusionQuery.h \
    core/include/hardwarebuffer/HardwarePixelBuffer.h \
    core/include/hardwarebuffer/HardwareUniformBuffer.h \
    core/include/hardwarebuffer/HardwareVertexBuffer.h \
    core/include/hardwarebuffer/RenderToVertexBuffer.h \
    core/include/hardwarebuffer/VertexIndexData.h \
    core/include/input/AbstractComponentProcessor.h \
    core/include/input/AbstractCursorInputEvt.h \
    core/include/input/AbstractCursorProcessor.h \
    core/include/input/AbstractGlobalInputProcessor.h \
    core/include/input/AbstractInputSource.h \
    core/include/input/AndroidInputManager.h \
    core/include/input/AndroidInputSource.h \
    core/include/input/ComponentInputProcessorSupport.h \
    core/include/input/DefaultDragAction.h \
    core/include/input/DefaultRotateAction.h \
    core/include/input/DefaultScaleAction.h \
    core/include/input/DragEvent.h \
    core/include/input/DragProcessor.h \
    core/include/input/Event.h \
    core/include/input/GestureEvent.h \
    core/include/input/GestureEventSupport.h \
    core/include/input/IClickListener.h \
    core/include/input/IGestureEventListener.h \
    core/include/input/IHitTestInfoProvider.h \
    core/include/input/IInputEventListener.h \
    core/include/input/IInputProcessor.h \
    core/include/input/IInputSourceListener.h \
    core/include/input/InputCursor.h \
    core/include/input/InputEvent.h \
    core/include/input/InputManager.h \
    core/include/input/InputRetargeter.h \
    core/include/input/ISurfaceTouchListener.h \
    core/include/input/PickInfo.h \
    core/include/input/PickResult.h \
    core/include/input/preinput.h \
    core/include/input/RotateEvent.h \
    core/include/input/RotateProcessor.h \
    core/include/input/ScaleEvent.h \
    core/include/input/ScaleProcessor.h \
    core/include/input/SensorListener.h \
    core/include/input/TapEvent.h \
    core/include/input/TapProcessor.h \
    core/include/io/Archive.h \
    core/include/io/ArchiveFactory.h \
    core/include/io/ArchiveManager.h \
    core/include/io/Codec.h \
    core/include/io/DataStream.h \
    core/include/io/FileSystem.h \
    core/include/io/Zip.h \
    core/include/parser/MeshParser.h \
    core/include/particle/Billboard.h \
    core/include/particle/BillboardParticleRenderer.h \
    core/include/particle/BillboardSet.h \
    core/include/particle/Particle.h \
    core/include/particle/ParticleAffector.h \
    core/include/particle/ParticleAffectorFactory.h \
    core/include/particle/ParticleEmitter.h \
    core/include/particle/ParticleEmitterFactory.h \
    core/include/particle/ParticleIterator.h \
    core/include/particle/ParticleSystem.h \
    core/include/particle/ParticleSystemManager.h \
    core/include/particle/ParticleSystemRenderer.h \
    core/include/platform/android/glsles/GLSLESExtSupport.h \
    core/include/platform/android/glsles/GLSLESProgramFactory.h \
    core/include/platform/android/glsles/GLSLLinkProgram.h \
    core/include/platform/android/glsles/GLSLLinkProgramManager.h \
    core/include/platform/android/glsles/GLSLPreprocessor.h \
    core/include/platform/android/glsles/GLSLProgram.h \
    core/include/ui/eButton.h \
    core/include/ui/eCube.h \
    core/include/ui/eGrid.h \
    core/include/ui/eRect.h \
    core/include/ui/eScorePanel.h \
    core/include/ui/OverlayElement.h \
    core/include/ui/OverlayElementCommands.h \
    core/include/ui/TextAreaOverlayElement.h \
    core/include/scripting/lua/auto_generated/lua_easy3d_auto.h \
    core/include/scripting/lua/Easy3dLuaLoader.h \
    core/include/scripting/lua/lua_easy3d_manual.h \
    core/include/scripting/lua/LuaBasicConversions.h \
    core/include/scripting/lua/LuaEngine.h \
    core/include/scripting/lua/LuaScriptHandlerMgr.h \
    core/include/scripting/lua/LuaStack.h \
    core/include/scripting/lua/LuaValue.h \
    core/include/scenegraph/AbstractScene.h \
    core/include/scenegraph/eGallery.h \
    core/include/scenegraph/GameObject.h \
    core/include/scenegraph/IAutoLayout.h \
    core/include/scenegraph/SceneManager.h \
    core/include/scenegraph/SceneManagerEnumerator.h \
    core/include/rendersystem/AutoParamDataSource.h \
    core/include/rendersystem/GpuProgram.h \
    core/include/rendersystem/GpuProgramParams.h \
    core/include/rendersystem/GpuProgramUsage.h \
    core/include/rendersystem/HighLevelGpuProgram.h \
    core/include/rendersystem/HighLevelGpuProgramManager.h \
    core/include/rendersystem/Material.h \
    core/include/rendersystem/MaterialManager.h \
    core/include/rendersystem/MeshFilter.h \
    core/include/rendersystem/MeshRenderer.h \
    core/include/rendersystem/Pass.h \
    core/include/rendersystem/Renderer.h \
    core/include/rendersystem/RenderFunction.h \
    core/include/rendersystem/RenderOperation.h \
    core/include/rendersystem/RenderQueue.h \
    core/include/rendersystem/RenderSystemCapabilities.h \
    core/include/rendersystem/RenderTarget.h \
    core/include/rendersystem/RenderTargetListener.h \
    core/include/rendersystem/RenderTexture.h \
    core/include/rendersystem/RenderWindow.h \
    core/include/rendersystem/SkinnedMeshRenderer.h \
    core/include/rendersystem/Texture.h \
    core/include/rendersystem/TextureManager.h \
    core/include/rendersystem/TextureUnitState.h \
    core/include/platform/android/StateCacheManager/GLES2NullStateCacheManagerImp.h \
    core/include/platform/android/StateCacheManager/OgreGLES2NullUniformCacheImp.h \
    core/include/platform/android/StateCacheManager/OgreGLES2StateCacheManagerImp.h \
    core/include/platform/android/StateCacheManager/OgreGLES2UniformCacheImp.h \
    core/include/platform/android/AndroidEGLRenderWindow.h \
    core/include/platform/android/AndroidLogManager.h \
    core/include/platform/android/GLES2DefaultHardwareBufferManager.h \
    core/include/platform/android/GLES2DepthBuffer.h \
    core/include/platform/android/GLES2FBOMultiRenderTarget.h \
    core/include/platform/android/GLES2FBORenderTexture.h \
    core/include/platform/android/GLES2FrameBufferObject.h \
    core/include/platform/android/GLES2HardwareBufferManager.h \
    core/include/platform/android/GLES2HardwareIndexBuffer.h \
    core/include/platform/android/GLES2HardwareOcclusionQuery.h \
    core/include/platform/android/GLES2HardwarePixelBuffer.h \
    core/include/platform/android/GLES2HardwareUniformBuffer.h \
    core/include/platform/android/GLES2HardwareVertexBuffer.h \
    core/include/platform/android/GLES2PixelFormat.h \
    core/include/platform/android/GLES2Prerequisites.h \
    core/include/platform/android/GLES2RenderFunction.h \
    core/include/platform/android/GLES2RenderTexture.h \
    core/include/platform/android/GLES2RenderToVertexBuffer.h \
    core/include/platform/android/GLES2StateCacheManager.h \
    core/include/platform/android/GLES2Support.h \
    core/include/platform/android/GLES2Texture.h \
    core/include/platform/android/GLES2TextureManager.h \
    core/include/platform/android/GLES2VertexDeclaration.h \
    core/include/platform/android/gles2w.h \
    core/include/external/particle/AreaEmitter.h \
    core/include/external/particle/BoxEmitter.h \
    core/include/external/particle/BoxEmitterFactory.h \
    core/include/external/particle/ColourFaderAffector.h \
    core/include/external/particle/ColourFaderAffector2.h \
    core/include/external/particle/ColourFaderAffectorFactory.h \
    core/include/external/particle/ColourFaderAffectorFactory2.h \
    core/include/external/particle/ColourInterpolatorAffector.h \
    core/include/external/particle/ColourInterpolatorAffectorFactory.h \
    core/include/external/particle/DirectionRandomiserAffector.h \
    core/include/external/particle/DirectionRandomiserAffectorFactory.h \
    core/include/external/particle/LinearForceAffector.h \
    core/include/external/particle/LinearForceAffectorFactory.h \
    core/include/external/particle/ParticleEmitterCommands.h \
    core/include/external/particle/ParticlePrerequisites.h \
    core/include/external/particle/PointEmitter.h \
    core/include/external/particle/PointEmitterFactory.h \
    core/include/external/particle/RandomCurveAffector.h \
    core/include/external/particle/RandomCurveAffectorFactory.h \
    core/include/external/particle/RotationAffector.h \
    core/include/external/particle/RotationAffectorFactory.h \
    core/include/external/particle/ScaleAffector.h \
    core/include/external/particle/ScaleAffectorFactory.h \
    core/include/external/particle/TextureAffector.h \
    core/include/external/particle/TextureAffectorFactory.h \
    core/include/external/particle/TextureFrameAffector.h \
    core/include/external/particle/TextureFrameAffectorFactory.h \
    core/include/external/tiny_xml/tinystr.h \
    core/include/external/tiny_xml/tinyxml.h \
    core/include/external/transport/MySocket.h \
    core/include/external/transport/VerifyLicense.h \
    core/include/external/AESEncrypt.h \
    core/include/external/JPGCodec.h \
    core/include/external/PNGCodec.h \
    core/include/external/PVRCodec.h \
    core/include/external/TGAParser.h \
    core/UI3dStore.h \
    external/libfreetype/include/freetype2/config/ftconfig.h \
    external/libfreetype/include/freetype2/config/ftheader.h \
    external/libfreetype/include/freetype2/config/ftmodule.h \
    external/libfreetype/include/freetype2/config/ftoption.h \
    external/libfreetype/include/freetype2/config/ftstdlib.h \
    external/libfreetype/include/freetype2/freetype.h \
    external/libfreetype/include/freetype2/ft2build.h \
    external/libfreetype/include/freetype2/ftadvanc.h \
    external/libfreetype/include/freetype2/ftautoh.h \
    external/libfreetype/include/freetype2/ftbbox.h \
    external/libfreetype/include/freetype2/ftbdf.h \
    external/libfreetype/include/freetype2/ftbitmap.h \
    external/libfreetype/include/freetype2/ftbzip2.h \
    external/libfreetype/include/freetype2/ftcache.h \
    external/libfreetype/include/freetype2/ftcffdrv.h \
    external/libfreetype/include/freetype2/ftchapters.h \
    external/libfreetype/include/freetype2/ftcid.h \
    external/libfreetype/include/freetype2/fterrdef.h \
    external/libfreetype/include/freetype2/fterrors.h \
    external/libfreetype/include/freetype2/ftgasp.h \
    external/libfreetype/include/freetype2/ftglyph.h \
    external/libfreetype/include/freetype2/ftgxval.h \
    external/libfreetype/include/freetype2/ftgzip.h \
    external/libfreetype/include/freetype2/ftimage.h \
    external/libfreetype/include/freetype2/ftincrem.h \
    external/libfreetype/include/freetype2/ftlcdfil.h \
    external/libfreetype/include/freetype2/ftlist.h \
    external/libfreetype/include/freetype2/ftlzw.h \
    external/libfreetype/include/freetype2/ftmac.h \
    external/libfreetype/include/freetype2/ftmm.h \
    external/libfreetype/include/freetype2/ftmodapi.h \
    external/libfreetype/include/freetype2/ftmoderr.h \
    external/libfreetype/include/freetype2/ftotval.h \
    external/libfreetype/include/freetype2/ftoutln.h \
    external/libfreetype/include/freetype2/ftpfr.h \
    external/libfreetype/include/freetype2/ftrender.h \
    external/libfreetype/include/freetype2/ftsizes.h \
    external/libfreetype/include/freetype2/ftsnames.h \
    external/libfreetype/include/freetype2/ftstroke.h \
    external/libfreetype/include/freetype2/ftsynth.h \
    external/libfreetype/include/freetype2/ftsystem.h \
    external/libfreetype/include/freetype2/fttrigon.h \
    external/libfreetype/include/freetype2/ftttdrv.h \
    external/libfreetype/include/freetype2/fttypes.h \
    external/libfreetype/include/freetype2/ftwinfnt.h \
    external/libfreetype/include/freetype2/ftxf86.h \
    external/libfreetype/include/freetype2/t1tables.h \
    external/libfreetype/include/freetype2/ttnameid.h \
    external/libfreetype/include/freetype2/tttables.h \
    external/libfreetype/include/freetype2/tttags.h \
    external/libfreetype/include/freetype2/ttunpat.h \
    external/libjpeg/include/cderror.h \
    external/libjpeg/include/cdjpeg.h \
    external/libjpeg/include/jconfig.h \
    external/libjpeg/include/jdct.h \
    external/libjpeg/include/jerror.h \
    external/libjpeg/include/jinclude.h \
    external/libjpeg/include/jmemsys.h \
    external/libjpeg/include/jmorecfg.h \
    external/libjpeg/include/jpegint.h \
    external/libjpeg/include/jpeglib.h \
    external/libjpeg/include/jversion.h \
    external/libjpeg/include/transupp.h \
    external/liblua/include/lua/lapi.h \
    external/liblua/include/lua/lauxlib.h \
    external/liblua/include/lua/lcode.h \
    external/liblua/include/lua/ldebug.h \
    external/liblua/include/lua/ldo.h \
    external/liblua/include/lua/lfunc.h \
    external/liblua/include/lua/lgc.h \
    external/liblua/include/lua/llex.h \
    external/liblua/include/lua/llimits.h \
    external/liblua/include/lua/lmem.h \
    external/liblua/include/lua/lobject.h \
    external/liblua/include/lua/lopcodes.h \
    external/liblua/include/lua/lparser.h \
    external/liblua/include/lua/lstate.h \
    external/liblua/include/lua/lstring.h \
    external/liblua/include/lua/ltable.h \
    external/liblua/include/lua/ltm.h \
    external/liblua/include/lua/lua.h \
    external/liblua/include/lua/luaconf.h \
    external/liblua/include/lua/lualib.h \
    external/liblua/include/lua/lundump.h \
    external/liblua/include/lua/lvm.h \
    external/liblua/include/lua/lzio.h \
    external/liblua/include/luajit/include/lauxlib.h \
    external/liblua/include/luajit/include/lua.h \
    external/liblua/include/luajit/include/luaconf.h \
    external/liblua/include/luajit/include/lualib.h \
    external/liblua/include/tolua/tolua_event.h \
    external/liblua/include/tolua/tolua_fix.h \
    external/liblua/include/tolua/tolua++.h \
    external/libpng/include/config.h \
    external/libpng/include/png.h \
    external/libpng/include/pngconf.h \
    external/libpng/include/pngpriv.h \
    external/libpvr/include/OGLES2/OGLES2Tools.h \
    external/libpvr/include/PVRParserUtils.h \
    external/libpvr/include/PVRTError.h \
    external/libpvr/include/PVRTexture.h \
    external/libpvr/include/PVRTFixedPoint.h \
    external/libpvr/include/PVRTGlobal.h \
    external/libutils/include/utils/include/android/TimerImp.h \
    external/libutils/include/utils/include/threading/ThreadDefines.h \
    external/libutils/include/utils/include/threading/ThreadDefinesNone.h \
    external/libutils/include/utils/include/win32/TimerImp.h \
    external/libutils/include/utils/include/asm_math.h \
    external/libutils/include/utils/include/AtomicScalar.h \
    external/libutils/include/utils/include/AxisAlignedBox.h \
    external/libutils/include/utils/include/Bitwise.h \
    external/libutils/include/utils/include/BlendMode.h \
    external/libutils/include/utils/include/Color.h \
    external/libutils/include/utils/include/ColourValue.h \
    external/libutils/include/utils/include/Common.h \
    external/libutils/include/utils/include/debug_flags.h \
    external/libutils/include/utils/include/eBaseAdapter.h \
    external/libutils/include/utils/include/IDGenerator.h \
    external/libutils/include/utils/include/IteratorRange.h \
    external/libutils/include/utils/include/IteratorWrapper.h \
    external/libutils/include/utils/include/IteratorWrappers.h \
    external/libutils/include/utils/include/mathlib.h \
    external/libutils/include/utils/include/Matrix3.h \
    external/libutils/include/utils/include/Matrix4.h \
    external/libutils/include/utils/include/MemoryAllocatorConfig.h \
    external/libutils/include/utils/include/MovablePlane.h \
    external/libutils/include/utils/include/NameGenerator.h \
    external/libutils/include/utils/include/PixelConversions.h \
    external/libutils/include/utils/include/PixelFormat.h \
    external/libutils/include/utils/include/Plane.h \
    external/libutils/include/utils/include/PlaneBoundedVolume.h \
    external/libutils/include/utils/include/platform.h \
    external/libutils/include/utils/include/prerequisites.h \
    external/libutils/include/utils/include/Quaternion.h \
    external/libutils/include/utils/include/Ray.h \
    external/libutils/include/utils/include/SharedPtr.h \
    external/libutils/include/utils/include/Singleton.h \
    external/libutils/include/utils/include/Sphere.h \
    external/libutils/include/utils/include/STDint.h \
    external/libutils/include/utils/include/String.h \
    external/libutils/include/utils/include/StringConverter.h \
    external/libutils/include/utils/include/StringVector.h \
    external/libutils/include/utils/include/Timer.h \
    external/libutils/include/utils/include/Transform.h \
    external/libutils/include/utils/include/Transformation.h \
    external/libutils/include/utils/include/UTFString.h \
    external/libutils/include/utils/include/Vector2.h \
    external/libutils/include/utils/include/Vector3.h \
    external/libutils/include/utils/include/Vector4.h \
    external/libzzip/include/zzip/__debug.h \
    external/libzzip/include/zzip/__dirent.h \
    external/libzzip/include/zzip/__fnmatch.h \
    external/libzzip/include/zzip/__hints.h \
    external/libzzip/include/zzip/__mmap.h \
    external/libzzip/include/zzip/_config.h \
    external/libzzip/include/zzip/_msvc.h \
    external/libzzip/include/zzip/autoconf.h \
    external/libzzip/include/zzip/conf.h \
    external/libzzip/include/zzip/fetch.h \
    external/libzzip/include/zzip/file.h \
    external/libzzip/include/zzip/format.h \
    external/libzzip/include/zzip/fseeko.h \
    external/libzzip/include/zzip/info.h \
    external/libzzip/include/zzip/lib.h \
    external/libzzip/include/zzip/memdisk.h \
    external/libzzip/include/zzip/mmapped.h \
    external/libzzip/include/zzip/plugin.h \
    external/libzzip/include/zzip/stdint.h \
    external/libzzip/include/zzip/types.h \
    external/libzzip/include/zzip/write.h \
    external/libzzip/include/zzip/zzip.h \
    external/libzzip/include/zzip/zzip32.h \
    external/zlib/include/crc32.h \
    external/zlib/include/deflate.h \
    external/zlib/include/gzguts.h \
    external/zlib/include/inffast.h \
    external/zlib/include/inffixed.h \
    external/zlib/include/inflate.h \
    external/zlib/include/inftrees.h \
    external/zlib/include/trees.h \
    external/zlib/include/zconf.h \
    external/zlib/include/zlib.h \
    external/zlib/include/zutil.h

FORMS    +=

OTHER_FILES += \
    external/liblua/include/lua/CMakeLists.txt
